#pragma once

#include <QString>
#include <QVector>

struct CodingTestCase {
    QString input;          // fed to the submitted program's stdin
    QString expectedOutput; // compared against stdout, trimmed on both sides
};

struct CodingProblem {
    QString id;
    QString title;
    QString difficulty; // "Easy" | "Medium" | "Hard"
    QString description;
    QString starterCode;
    QVector<CodingTestCase> sampleTests; // shown to the user, run by "Run Sample Tests"
    QVector<CodingTestCase> hiddenTests; // only run by "Submit", not shown
};

/**
 * The Coding Interview Module's problem set (spec module 12): each problem
 * reads from stdin and writes to stdout, the same style used by
 * Codeforces/CSES, since that's the judge format CodingJudge implements
 * (compile once, run the binary once per test case, compare trimmed stdout).
 *
 * 27 problems across Easy/Medium/Hard, covering classic DSA topics:
 * arrays, strings, searching, sorting, stacks, DP, graphs. Every sample and
 * hidden test case here was generated by actually running a reference
 * solution (not hand-computed), so expected outputs are verified correct.
 */
namespace CodingProblemBank {

inline const QVector<CodingProblem> &all()
{
    static const QVector<CodingProblem> kProblems = {
        CodingProblem{
            "sum_array",
            "Sum of Array Elements",
            "Easy",
            "Given n integers, print their sum.\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  the sum",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<long long> a(n);for(auto&x:a)cin>>x;\n// TODO: print the sum\ncout<<0<<endl;return 0;}\n",
            {
                {"5\n1 2 3 4 5", "15"},
                {"3\n-1 -2 -3", "-6"},
            },
            {
                {"1\n100", "100"},
                {"4\n0 0 0 0", "0"},
                {"6\n10 -5 3 8 -2 1", "15"},
            },
        },
        CodingProblem{
            "reverse_string",
            "Reverse a String",
            "Easy",
            "Given a string, print it reversed.\n\nInput:\n  one line: the string (no spaces)\nOutput:\n  the reversed string",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// TODO: print s reversed\ncout<<s<<endl;return 0;}\n",
            {
                {"hello", "olleh"},
                {"abcd", "dcba"},
            },
            {
                {"a", "a"},
                {"racecar", "racecar"},
                {"programming", "gnimmargorp"},
            },
        },
        CodingProblem{
            "factorial",
            "Factorial",
            "Easy",
            "Given n (0 <= n <= 15), print n! (factorial).\n\nInput:\n  one line: n\nOutput:\n  n!",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;\n// TODO: compute factorial\ncout<<1<<endl;return 0;}\n",
            {
                {"5", "120"},
                {"0", "1"},
            },
            {
                {"1", "1"},
                {"10", "3628800"},
                {"12", "479001600"},
            },
        },
        CodingProblem{
            "check_prime",
            "Check Prime",
            "Easy",
            "Given an integer n, print YES if it is prime, otherwise NO.\n\nInput:\n  one line: n\nOutput:\n  YES or NO",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){long long n;cin>>n;\n// TODO: check primality\ncout<<\"NO\"<<endl;return 0;}\n",
            {
                {"7", "YES"},
                {"10", "NO"},
            },
            {
                {"1", "NO"},
                {"2", "YES"},
                {"97", "YES"},
                {"100", "NO"},
            },
        },
        CodingProblem{
            "gcd_two",
            "GCD of Two Numbers",
            "Easy",
            "Given two positive integers, print their GCD.\n\nInput:\n  one line: a b\nOutput:\n  gcd(a, b)",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){long long a,b;cin>>a>>b;\n// TODO: compute gcd\ncout<<0<<endl;return 0;}\n",
            {
                {"12 18", "6"},
                {"7 13", "1"},
            },
            {
                {"100 75", "25"},
                {"1 1", "1"},
                {"1000000 1", "1"},
            },
        },
        CodingProblem{
            "count_vowels",
            "Count Vowels",
            "Easy",
            "Given a lowercase string, print the number of vowels (a, e, i, o, u) in it.\n\nInput:\n  one line: the string\nOutput:\n  vowel count",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// TODO: count vowels\ncout<<0<<endl;return 0;}\n",
            {
                {"hello", "2"},
                {"rhythm", "0"},
            },
            {
                {"aeiou", "5"},
                {"xyz", "0"},
                {"programming", "3"},
            },
        },
        CodingProblem{
            "max_element",
            "Find Maximum in Array",
            "Easy",
            "Given n integers, print the maximum value.\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  the maximum",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<long long> a(n);for(auto&x:a)cin>>x;\n// TODO: print max\ncout<<0<<endl;return 0;}\n",
            {
                {"4\n3 7 2 9", "9"},
                {"3\n-5 -1 -9", "-1"},
            },
            {
                {"1\n42", "42"},
                {"5\n1 1 1 1 1", "1"},
                {"6\n-10 -20 5 3 100 -1", "100"},
            },
        },
        CodingProblem{
            "nth_fibonacci",
            "Nth Fibonacci Number",
            "Easy",
            "Given n (0-indexed, fib(0)=0, fib(1)=1), print the nth Fibonacci number.\n\nInput:\n  one line: n\nOutput:\n  fib(n)",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;\n// TODO: compute nth fibonacci\ncout<<0<<endl;return 0;}\n",
            {
                {"0", "0"},
                {"5", "5"},
            },
            {
                {"1", "1"},
                {"10", "55"},
                {"20", "6765"},
            },
        },
        CodingProblem{
            "armstrong",
            "Check Armstrong Number",
            "Easy",
            "An Armstrong number equals the sum of its own digits each raised to the power of the number of digits (e.g. 153 = 1^3+5^3+3^3). Given n, print YES or NO.\n\nInput:\n  one line: n\nOutput:\n  YES or NO",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string n;cin>>n;\n// TODO: check armstrong\ncout<<\"NO\"<<endl;return 0;}\n",
            {
                {"153", "YES"},
                {"123", "NO"},
            },
            {
                {"9474", "YES"},
                {"10", "NO"},
                {"0", "YES"},
            },
        },
        CodingProblem{
            "binary_search",
            "Binary Search",
            "Easy",
            "Given a sorted array and a target, print the 1-indexed position of target, or -1 if not present.\n\nInput:\n  line 1: n target\n  line 2: n sorted integers\nOutput:\n  1-indexed position or -1",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;long long target;cin>>n>>target;vector<long long> a(n);for(auto&x:a)cin>>x;\n// TODO: binary search\ncout<<-1<<endl;return 0;}\n",
            {
                {"5 7\n1 3 5 7 9", "4"},
                {"4 6\n2 4 8 10", "-1"},
            },
            {
                {"1 5\n5", "1"},
                {"6 1\n1 2 3 4 5 6", "1"},
                {"3 100\n1 2 3", "-1"},
            },
        },
        CodingProblem{
            "two_sum",
            "Two Sum (Sorted Array)",
            "Medium",
            "Given a sorted array of n integers and a target value, print the 1-indexed positions of the two numbers that add up to target, space-separated. If no pair works, print \"No solution\".\n\nInput:\n  line 1: n target\n  line 2: n sorted integers\nOutput:\n  \"i j\" (i < j), or \"No solution\"",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;long long target;cin>>n>>target;vector<long long> a(n);for(auto&x:a)cin>>x;\n// TODO: find the pair\ncout<<\"No solution\"<<endl;return 0;}\n",
            {
                {"4 9\n2 7 11 15", "1 2"},
                {"3 6\n1 2 3", "No solution"},
            },
            {
                {"5 10\n1 2 3 7 9", "3 4"},
                {"2 100\n50 50", "1 2"},
            },
        },
        CodingProblem{
            "kadane",
            "Maximum Subarray Sum",
            "Medium",
            "Given n integers (can be negative), print the maximum sum of any contiguous subarray (Kadane's algorithm). At least one element must be chosen.\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  the maximum sum",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<long long> a(n);for(auto&x:a)cin>>x;\n// TODO: Kadane's algorithm\ncout<<0<<endl;return 0;}\n",
            {
                {"5\n-2 1 -3 4 -1", "4"},
                {"3\n-1 -2 -3", "-1"},
            },
            {
                {"8\n-2 1 -3 4 -1 2 1 -5", "6"},
                {"1\n5", "5"},
            },
        },
        CodingProblem{
            "reverse_array",
            "Reverse an Array",
            "Medium",
            "Given n integers, print them in reverse order, space-separated.\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  the reversed array",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<int> a(n);for(auto&x:a)cin>>x;\n// TODO: print a in reverse\nreturn 0;}\n",
            {
                {"4\n1 2 3 4", "4 3 2 1"},
            },
            {
                {"1\n7", "7"},
                {"5\n10 20 30 40 50", "50 40 30 20 10"},
            },
        },
        CodingProblem{
            "merge_sorted",
            "Merge Two Sorted Arrays",
            "Medium",
            "Given two sorted arrays of sizes n and m, print the merged sorted array, space-separated.\n\nInput:\n  line 1: n m\n  line 2: n integers (array A)\n  line 3: m integers (array B)\nOutput:\n  merged sorted array",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,m;cin>>n>>m;vector<int> a(n),b(m);for(auto&x:a)cin>>x;for(auto&x:b)cin>>x;\n// TODO: merge both sorted arrays\nreturn 0;}\n",
            {
                {"3 2\n1 3 5\n2 4", "1 2 3 4 5"},
                {"2 3\n1 2\n1 2 3", "1 1 2 2 3"},
            },
            {
                {"4 0\n1 2 3 4\n", "1 2 3 4"},
                {"1 1\n5\n3", "3 5"},
            },
        },
        CodingProblem{
            "valid_parentheses",
            "Valid Parentheses",
            "Medium",
            "Given a string of only (){}[] characters, print YES if brackets are balanced/nested correctly, otherwise NO.\n\nInput:\n  one line: the string\nOutput:\n  YES or NO",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// TODO: check balanced brackets using a stack\ncout<<\"NO\"<<endl;return 0;}\n",
            {
                {"([]{})", "YES"},
                {"([)]", "NO"},
            },
            {
                {"((()))", "YES"},
                {"{[()]}", "YES"},
                {"(((", "NO"},
            },
        },
        CodingProblem{
            "count_inversions",
            "Count Inversions",
            "Medium",
            "Given n integers, count the number of pairs (i, j) with i < j and arr[i] > arr[j] (inversions).\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  number of inversions",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<int> a(n);for(auto&x:a)cin>>x;\n// TODO: count inversions\ncout<<0<<endl;return 0;}\n",
            {
                {"5\n2 4 1 3 5", "3"},
                {"3\n3 2 1", "3"},
            },
            {
                {"4\n1 2 3 4", "0"},
                {"6\n6 5 4 3 2 1", "15"},
            },
        },
        CodingProblem{
            "first_unique_char",
            "First Non-Repeating Character",
            "Medium",
            "Given a lowercase string, print the 1-indexed position of the first character that appears exactly once, or -1 if none.\n\nInput:\n  one line: the string\nOutput:\n  1-indexed position or -1",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// TODO: find first non-repeating character\ncout<<-1<<endl;return 0;}\n",
            {
                {"leetcode", "1"},
                {"aabb", "-1"},
            },
            {
                {"a", "1"},
                {"aabbcddc", "-1"},
                {"xyzzy", "1"},
            },
        },
        CodingProblem{
            "rotate_array",
            "Rotate Array by K",
            "Medium",
            "Given n integers and k, rotate the array to the right by k steps and print it.\n\nInput:\n  line 1: n k\n  line 2: n integers\nOutput:\n  the rotated array, space-separated",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,k;cin>>n>>k;vector<int> a(n);for(auto&x:a)cin>>x;\n// TODO: rotate right by k\nreturn 0;}\n",
            {
                {"5 2\n1 2 3 4 5", "4 5 1 2 3"},
                {"4 1\n1 2 3 4", "4 1 2 3"},
            },
            {
                {"6 3\n1 2 3 4 5 6", "4 5 6 1 2 3"},
                {"3 7\n1 2 3", "3 1 2"},
            },
        },
        CodingProblem{
            "lis_length",
            "Longest Increasing Subsequence",
            "Medium",
            "Given n integers, print the length of the longest strictly increasing subsequence.\n\nInput:\n  line 1: n\n  line 2: n integers\nOutput:\n  length of the LIS",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;vector<int> a(n);for(auto&x:a)cin>>x;\n// TODO: DP for LIS length\ncout<<0<<endl;return 0;}\n",
            {
                {"8\n10 9 2 5 3 7 101 18", "4"},
                {"4\n1 2 3 4", "4"},
            },
            {
                {"1\n5", "1"},
                {"5\n5 4 3 2 1", "1"},
            },
        },
        CodingProblem{
            "kth_largest",
            "Kth Largest Element",
            "Medium",
            "Given n integers and k, print the kth largest element (1st largest is the maximum).\n\nInput:\n  line 1: n k\n  line 2: n integers\nOutput:\n  the kth largest value",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,k;cin>>n>>k;vector<int> a(n);for(auto&x:a)cin>>x;\n// TODO: find kth largest\ncout<<0<<endl;return 0;}\n",
            {
                {"6 2\n3 2 1 5 6 4", "5"},
                {"5 1\n1 2 3 4 5", "5"},
            },
            {
                {"4 4\n8 1 3 5", "1"},
                {"7 3\n7 7 7 1 1 1 1", "7"},
            },
        },
        CodingProblem{
            "lcs",
            "Longest Common Subsequence",
            "Hard",
            "Given two strings, print the length of their longest common subsequence.\n\nInput:\n  line 1: string A\n  line 2: string B\nOutput:\n  length of the LCS",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string a,b;cin>>a>>b;\n// TODO: LCS DP\ncout<<0<<endl;return 0;}\n",
            {
                {"abcde\nace", "3"},
                {"abc\nabc", "3"},
            },
            {
                {"abcba\nabcbcba", "5"},
                {"abc\ndef", "0"},
            },
        },
        CodingProblem{
            "edit_distance",
            "Edit Distance",
            "Hard",
            "Given two strings, print the minimum number of insert/delete/replace operations to convert the first into the second.\n\nInput:\n  line 1: string A\n  line 2: string B\nOutput:\n  minimum edit distance",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string a,b;cin>>a>>b;\n// TODO: edit distance DP\ncout<<0<<endl;return 0;}\n",
            {
                {"horse\nros", "3"},
                {"intention\nexecution", "5"},
            },
            {
                {"abc\nabc", "0"},
                {"\nabc", "3"},
            },
        },
        CodingProblem{
            "knapsack01",
            "0/1 Knapsack",
            "Hard",
            "Given n items with weights and values, and a knapsack capacity, print the maximum total value achievable without exceeding the capacity (each item used at most once).\n\nInput:\n  line 1: n capacity\n  line 2: n weights\n  line 3: n values\nOutput:\n  maximum value",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,cap;cin>>n>>cap;vector<int> w(n),v(n);for(auto&x:w)cin>>x;for(auto&x:v)cin>>x;\n// TODO: 0/1 knapsack DP\ncout<<0<<endl;return 0;}\n",
            {
                {"3 50\n10 20 30\n60 100 120", "220"},
                {"4 10\n5 4 6 3\n10 40 30 50", "90"},
            },
            {
                {"1 10\n5\n100", "100"},
                {"2 5\n6 6\n10 10", "0"},
            },
        },
        CodingProblem{
            "coin_change",
            "Coin Change (Minimum Coins)",
            "Hard",
            "Given n coin denominations and a target amount, print the minimum number of coins needed to make that amount, or -1 if impossible.\n\nInput:\n  line 1: n amount\n  line 2: n coin denominations\nOutput:\n  minimum coins, or -1",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,amount;cin>>n>>amount;vector<int> c(n);for(auto&x:c)cin>>x;\n// TODO: coin change DP\ncout<<-1<<endl;return 0;}\n",
            {
                {"3 11\n1 2 5", "3"},
                {"1 3\n2", "-1"},
            },
            {
                {"2 0\n1 2", "0"},
                {"3 100\n1 5 10", "10"},
            },
        },
        CodingProblem{
            "has_topo_order",
            "Detect Cycle (Topological Order Exists?)",
            "Hard",
            "Given a directed graph with n nodes (1-indexed) and e edges, print YES if the graph has no cycle (a topological order exists), otherwise NO.\n\nInput:\n  line 1: n e\n  next e lines: u v (edge u -> v)\nOutput:\n  YES or NO",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,e;cin>>n>>e;vector<vector<int>> adj(n+1);vector<int> indeg(n+1,0);for(int i=0;i<e;i++){int u,v;cin>>u>>v;adj[u].push_back(v);indeg[v]++;}\n// TODO: Kahn's algorithm for cycle detection\ncout<<\"NO\"<<endl;return 0;}\n",
            {
                {"4 4\n1 2\n2 3\n3 4\n1 3", "YES"},
                {"3 3\n1 2\n2 3\n3 1", "NO"},
            },
            {
                {"5 0", "YES"},
                {"3 3\n1 2\n2 3\n1 3", "YES"},
            },
        },
        CodingProblem{
            "longest_palindromic_substring",
            "Longest Palindromic Substring (Length)",
            "Hard",
            "Given a string, print the length of its longest palindromic substring.\n\nInput:\n  one line: the string\nOutput:\n  length of the longest palindromic substring",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// TODO: expand-around-center or DP\ncout<<0<<endl;return 0;}\n",
            {
                {"babad", "3"},
                {"cbbd", "2"},
            },
            {
                {"a", "1"},
                {"aaaa", "4"},
                {"abcde", "1"},
            },
        },
        CodingProblem{
            "dijkstra_shortest_path",
            "Shortest Path (Dijkstra)",
            "Hard",
            "Given an undirected weighted graph with n nodes (1-indexed) and e edges, print the shortest distance from src to dst, or -1 if unreachable.\n\nInput:\n  line 1: n e src dst\n  next e lines: u v w (edge u-v with weight w)\nOutput:\n  shortest distance, or -1",
            "#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n,e,src,dst;cin>>n>>e>>src>>dst;vector<vector<pair<int,int>>> adj(n+1);for(int i=0;i<e;i++){int u,v,w;cin>>u>>v>>w;adj[u].push_back({v,w});adj[v].push_back({u,w});}\n// TODO: Dijkstra's algorithm\ncout<<-1<<endl;return 0;}\n",
            {
                {"5 6 1 5\n1 2 2\n1 3 4\n2 3 1\n2 4 7\n3 5 3\n4 5 1", "6"},
                {"3 1 1 3\n1 2 5", "-1"},
            },
            {
                {"4 2 1 4\n1 2 1\n3 4 1", "-1"},
                {"2 1 1 2\n1 2 10", "10"},
            },
        },
    };
    return kProblems;
}

} // namespace CodingProblemBank
